# Production Docker Compose project
version: '3'
services:
  db:
    image: postgres
    restart: unless-stopped
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  web:
    build: .
    command: bash -c "python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate && gunicorn --workers=3 config.wsgi -b 0.0.0.0:8000"
    volumes:
      - .:/app
      - static:/app/staticfiles
      - media:/app/media
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE
      - SECRET_KEY
      - POSTGRES_NAME
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    depends_on:
      - db

  caddy:
    image: abiosoft/caddy
    environment:
      ACME_AGREE: "true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/srv
      - ./Caddyfile:/etc/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - caddy_certs:/root/.caddy
      - media:/app/media
      - static:/app/staticfiles

volumes:
  pgdata:
  caddy_certs:
  caddy_data:
  caddy_config:
  static:
  media: