# Production Docker Compose project
version: '3'
services:
  db:
    image: postgres
    restart: unless-stopped
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=gcdb
      - POSTGRES_USER=gcuser
      - POSTGRES_PASSWORD=temp_password

  web:
    build: .
    command: bash -c "python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate && gunicorn --workers=3 config.wsgi -b 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE
      - POSTGRES_NAME=gcdb
      - POSTGRES_USER=gcuser
      - POSTGRES_PASSWORD=temp_password
    depends_on:
      - db

  caddy:
    image: abiosoft/caddy
    depends_on:
      - web
    restart: always
    environment:
      ACME_AGREE: "true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - caddy_certs:/root/.caddy

volumes:
  pgdata:
  caddy_certs: