version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE
      - SECRET_KEY
      - POSTGRES_NAME
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - ALPHA_PASSWORD
      - EMAIL_PASSWORD
      - EMAIL_HOST
      - EMAIL_PORT
      - EMAIL_USER
    depends_on:
      - db

  db2:
    image: postgres
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  directus:
    image: directus/directus:10
    ports:
      - 8055:8055
    volumes:
      - ./volumes/directus/database:/directus/database
      - ./volumes/directus/uploads:/directus/uploads
    environment:
      - KEY
      - SECRET
      - DB_CLIENT
      - DB_HOST
      - DB_PORT
      - DB_DATABASE
      - DB_USER
      - DB_PASSWORD
      - ADMIN_EMAIL
      - ADMIN_PASSWORD
      - EMAIL_TRANSPORT
      - EMAIL_SMTP_HOST
      - EMAIL_SMTP_NAME
      - EMAIL_SMTP_USER
      - EMAIL_SMTP_PASSWORD
      - EMAIL_SMTP_PORT
      - EMAIL_SMTP_SECURE
      - EMAIL_IGNORE_TLS
      - EMAIL_FROM
    depends_on:
      - db2
    restart: unless-stopped