services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE
      - SECRET_KEY
      - POSTGRES_NAME
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - ASSETS_STORAGE_URL
    depends_on:
      - db