# Generated by Django 5.0 on 2024-03-30 08:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_invitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GCUser',
            new_name='Profile',
        ),
        migrations.AlterField(
            model_name='invitation',
            name='code',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
