# Generated by Django 5.0 on 2024-04-01 06:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_rename_gcuser_profile_alter_invitation_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('name', models.CharField(max_length=127, unique=True)),
                ('model', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
