name: Deploy Live Web App

on: [push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: tashhhh4/graphicalchat@master
        with:
          host: ${{secrets.GC_BOX_IP}}
          username: ${{secrets.GC_BOX_USERNAME}}
          password: ${{secrets.GC_BOX_PASSWORD}}
          script: |
            cd /graphicalchat/app
            git pull
            docker compose down
            docker compose up -d