name: Deploy Live Web App

on: [push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.GC_BOX_IP}}
          username: ${{secrets.GC_BOX_USERNAME}}
          password: ${{secrets.GC_BOX_PASSWORD}}
          script: |
            cd /graphicalchat &&
            echo 'Just changed directory. now we are in:' &&
            pwd &&
            echo 'Before doing git pull' &&
            sudo git pull &&
            echo 'After doing git pull!' &&
            echo 'We will cd again' &&
            cd /graphicalchat/app &&
            echo 'Now we are in' &&
            pwd &&
            echo 'Now we try to rm' &&
            echo 'We are in:' &&
            pwd &&
            echo 'The files here:' &&
            ls -la &&