name: Deploy Live Web App

on: [push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.GC_BOX_IP}}
          username: ${{secrets.GC_BOX_USERNAME}}
          password: ${{secrets.GC_BOX_PASSWORD}}
          script: |
            cd /graphicalchat/app &&
            sudo git pull &&
            sudo docker compose down &&
            sudo docker compose up -d